Repository NetchX/Netch, pull requests merged in 2019-09, with the labels that each got.

#90 fix bugs
  Netch/Controllers/MainController.cs
  Netch/Controllers/SSController.cs
  Netch/Controllers/SSRController.cs
  Netch/Controllers/VMessController.cs
  Netch/Forms/MainForm.Designer.cs
  Netch/Forms/MainForm.cs
  Netch/Forms/MainForm.resx
Labels: Status: Review Needed, Type: Bug

#92 Add (close #52) http and socks5 local ports modification and saving
  Netch/Controllers/HTTPController.cs
  Netch/Controllers/NFController.cs
  Netch/Controllers/PrivoxyController.cs
  Netch/Controllers/SSController.cs
  Netch/Controllers/TUNTAPController.cs
  Netch/Forms/MainForm.cs
  Netch/Forms/SettingForm.Designer.cs
  Netch/Forms/SettingForm.cs
  Netch/Resources/zh-CN
Labels: Status: Accepted, Type: Enhancement

#97 Refactor configs to one file
  Netch/Controllers/HTTPController.cs
  Netch/Controllers/NFController.cs
  Netch/Controllers/PrivoxyController.cs
  Netch/Controllers/SSController.cs
  Netch/Controllers/TUNTAPController.cs
  Netch/Forms/GlobalBypassIPForm.cs
  Netch/Forms/MainForm.cs
  Netch/Forms/Server/Shadowsocks.cs
  Netch/Forms/Server/ShadowsocksR.cs
  Netch/Forms/Server/Socks5.cs
  Netch/Forms/Server/Vmess.cs
  Netch/Forms/SettingForm.Designer.cs
  Netch/Forms/SettingForm.cs
  Netch/Forms/SubscribeForm.cs
  Netch/Global.cs
  Netch/Netch.csproj
  Netch/Objects/Setting.cs
  Netch/Resources/zh-CN
  Netch/Utils/Configuration.cs
  docs/USAGE.zh-CN.md
Labels: Status: Review Needed, Type: Maintenance

#104 Add black and white NotifyIcon
  Netch/Resources/Netchiconblack.png
  Netch/Resources/Netchiconwhite.png
Labels: Status: Completed, Type: Enhancement

#108 Fix #107 maincontroller issues
  Netch/Controllers/MainController.cs
  Netch/Forms/MainForm.Designer.cs
Labels: Status: Review Needed, Type: Bug

#110 Fix Vmess SSR local Socks5 port setting
  Netch/Controllers/SSRController.cs
  Netch/Controllers/VMessController.cs
  Netch/Forms/SettingForm.cs
  Netch/Global.cs
  Netch/Netch.csproj
  Netch/Objects/Setting.cs
  Netch/Utils/Configuration.cs
  docs/README.zh-CN.md
Labels: Status: Review Needed

#113 Add custom local address (127.0.0.1 or 0.0.0.0)
  Netch/Controllers/HTTPController.cs
  Netch/Controllers/MainController.cs
  Netch/Controllers/NFController.cs
  Netch/Controllers/SSController.cs
  Netch/Controllers/SSRController.cs
  Netch/Controllers/VMessController.cs
  Netch/Forms/MainForm.cs
  Netch/Forms/SettingForm.Designer.cs
  Netch/Forms/SettingForm.cs
  Netch/Objects/Information/SSR.cs
  Netch/Objects/Setting.cs
  Netch/Resources/zh-CN
Labels: Status: Review Needed

#139 Fix #136 config saving issues
  Netch/Controllers/HTTPController.cs
  Netch/Controllers/PrivoxyController.cs
  Netch/Forms/GlobalBypassIPForm.cs
  Netch/Forms/MainForm.cs
  Netch/Forms/Server/Shadowsocks.Designer.cs
  Netch/Forms/Server/Shadowsocks.cs
  Netch/Forms/Server/ShadowsocksR.Designer.cs
  Netch/Forms/Server/ShadowsocksR.cs
  Netch/Forms/Server/Socks5.Designer.cs
  Netch/Forms/Server/Socks5.cs
  Netch/Forms/Server/Vmess.Designer.cs
  Netch/Forms/Server/Vmess.cs
  Netch/Forms/SettingForm.cs
  Netch/Forms/SubscribeForm.cs
Labels: Status: Review Needed, Type: Bug, Type: Enhancement
