Repository NetchX/Netch, pull requests merged in 2020-01, with the labels that each got.

#231 A simple profile UI which enables you to swtich to different profiles quickly
  Netch/Forms/MainForm.Designer.cs
  Netch/Forms/MainForm.cs
  Netch/Models/Profile.cs
  Netch/Models/Setting.cs
  Netch/Netch.csproj
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#241 Fix ssr & save wrong index cause by #239
  Netch/Forms/MainForm.cs
  Netch/Forms/Server/ShadowsocksR.Designer.cs
  Netch/Forms/Server/ShadowsocksR.cs
  Netch/Utils/ShareLink.cs
Labels: Priority: Low, Status: In Progress, Type: Bug

#242 Add shadowsocks subscription support
  Netch/Controllers/HTTPController.cs
  Netch/Controllers/MainController.cs
  Netch/Controllers/NFController.cs
  Netch/Controllers/PrivoxyController.cs
  Netch/Controllers/SSController.cs
  Netch/Controllers/SSRController.cs
  Netch/Controllers/TUNTAPController.cs
  Netch/Controllers/UpdateChecker.cs
  Netch/Controllers/VMessController.cs
  Netch/Forms/GlobalBypassIPForm.cs
  Netch/Forms/MainForm.cs
  Netch/Forms/Mode/Process.cs
  Netch/Forms/Server/Shadowsocks.cs
  Netch/Forms/Server/ShadowsocksR.cs
  Netch/Forms/Server/Socks5.cs
  Netch/Forms/Server/Vmess.cs
  Netch/Forms/SettingForm.cs
  Netch/Forms/SubscribeForm.cs
  Netch/Global.cs
  Netch/Models/LegacyServer.cs
  Netch/Models/LegacySetting.cs
  Netch/Models/Mode.cs
  Netch/Models/Profile.cs
  Netch/Models/SS/ShadowsocksServer.cs
  Netch/Models/Server.cs
  Netch/Models/Setting.cs
  Netch/Netch.cs
  Netch/Netch.csproj
  Netch/Override/SearchComboBox.cs
  Netch/Resolver.cs
  Netch/Resources/zh-CN
  Netch/Utils/Bandwidth.cs
  Netch/Utils/Configuration.cs
  Netch/Utils/Extensions.cs
  Netch/Utils/Logging.cs
  Netch/Utils/ShareLink.cs
  Netch/Win32Native.cs
Labels: Priority: Low, Status: Completed, Type: Enhancement
